sudo: required
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5.0
  - 2.6.0
  - 2.7.0
env:
  - CALC_VERSION=2.12.5.6
  - CALC_VERSION=2.12.6.3
before_install:
  - gem install bundler     # travis ruby 2.0.0 installs bundler 1.7, update it
  - bin/install_calc.sh
after_success:
  - bin/todo.rb
